window.XIPU_PROGRAM_REQUIREMENTS = {
  "帝国理工学院|MSc Science Communication": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/science-communication/", verified: "2026-08-20" },
  "帝国理工学院|MSc Advanced Computing": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/advanced-computing/", verified: "2026-08-20" },
  "帝国理工学院|MSc Strategic Marketing": { ielts: "7.0（单项6.5）", level: "Higher", gre: "非强制，可增强申请", source: "https://www.imperial.ac.uk/business-school/masters/strategic-marketing/admissions/", verified: "2026-08-20" },
  "帝国理工学院|MRes in Medical Robotics and Image-Guided Intervention": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/medical-robotics/", verified: "2026-08-20" },
  "帝国理工学院|MSc Applied Computational Science and Engineering": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/applied-computational-science/", verified: "2026-08-20" },
  "帝国理工学院|MSc Analogue and Digital Integrated Circuit Design": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/analogue-digital-circuit-design/", verified: "2026-08-20" },
  "帝国理工学院|MSc Financial Technology (Fintech)": { ielts: "7.0（单项6.5）", level: "Higher", gre: "非强制；量化背景较弱者建议提交，GRE Quant 159可增强", source: "https://www.imperial.ac.uk/business-school/masters/financial-technology/admissions/", verified: "2026-08-20" },
  "帝国理工学院|MSc Security and Resilience: Science and Technology": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/security-resilience-science-technology/", verified: "2026-08-20" },
  "帝国理工学院|MSc Transport": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/transport/", verified: "2026-08-20" },
  "帝国理工学院|MSc Global Health Management": { ielts: "7.0（单项6.5）", level: "Higher", gre: "非强制；量化背景较弱者强烈建议，建议90百分位", source: "https://www.imperial.ac.uk/business-school/masters/global-health-management/admissions/", verified: "2026-08-20" },
  "帝国理工学院|MRes Biomedical Research": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/biomedical-research/", verified: "2026-08-20" },
  "帝国理工学院|MSc Biomedical Engineering (Biomaterials)": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/biomedical-engineering-biomaterials/", verified: "2026-08-20" },
  "帝国理工学院|MSc Risk Management and Financial Engineering": { ielts: "7.0（单项6.5）", level: "Higher", gre: "非强制；量化背景较弱者建议提交，GRE Quant 159可增强", source: "https://www.imperial.ac.uk/business-school/masters/risk-management/admissions/", verified: "2026-08-20" },
  "帝国理工学院|MSc Advanced Computational Methods for Aeronautics, Flow Management and Fluid-Structure Interaction": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computational-methods/", verified: "2026-08-20" },
  "帝国理工学院|MSc Economics & Strategy for Business": { ielts: "7.0（单项6.5）", level: "Higher", gre: "非强制；量化背景较弱者建议提交，GRE Quant 159可增强", source: "https://www.imperial.ac.uk/business-school/masters/economics-strategy-business/admissions/", verified: "2026-08-20" },
  "帝国理工学院|MSc Future Power Networks": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/future-power-networks/", verified: "2026-08-20" },
  "帝国理工学院|MSc Transport with Data Science": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/transport-data-science/", verified: "2026-08-20" },
  "帝国理工学院|MRes Soft Electronic Materials": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/soft-electronic-materials/", verified: "2026-08-20" },
  "帝国理工学院|MSc Communications and Signal Processing": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/communications-signal-processing/", verified: "2026-08-20" },
  "帝国理工学院|MSc Environmental Data Science and Machine Learning": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/environmental-data-science-machine-learning/", verified: "2026-08-20" },
  "帝国理工学院|MSc Epidemiology": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/epidemiology/", verified: "2026-08-20" },
  "帝国理工学院|MSc Mathematics and Finance": { ielts: "7.0（单项6.5）", level: "Higher", gre: "不要求GRE/GMAT", source: "https://www.imperial.ac.uk/mathematics/postgraduate/msc/msc-in-applied-mathematics/prospective-students/", verified: "2026-08-20" },
  "帝国理工学院|MSc Applied Machine Learning": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/applied-machine-learning/", verified: "2026-08-20" },
  "帝国理工学院|MSc Applied Mathematics": { ielts: "6.5（单项6.0）", level: "Standard", gre: "不要求GRE/GMAT", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/applied-mathematics/", verified: "2026-08-20" },
  "帝国理工学院|MSc Artificial Intelligence Applications and Innovation": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/applications-innovation/", verified: "2026-08-20" },
  "帝国理工学院|MSc Control and Optimisation": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/control-optimisation/", verified: "2026-08-20" },
  "帝国理工学院|MSc Finance & Accounting": { ielts: "7.0（单项6.5）", level: "Higher", gre: "非强制；GRE Quant 159可增强，量化背景较弱者强烈建议", source: "https://www.imperial.ac.uk/business-school/masters/finance-accounting/admissions/", verified: "2026-08-20" },
  "帝国理工学院|MSc Geotechnical and Geoenvironmental Engineering": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/geotechnical-geoenvironmental-engineering/", verified: "2026-08-20" },
  "帝国理工学院|MSc Human and Biological Robotics": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/human-biological-robotics/", verified: "2026-08-20" },
  "帝国理工学院|MSc Renewable Energy with AI and Data Science: Geology and Geophysics": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/renewable-energy/", verified: "2026-08-20" },
  "帝国理工学院|MSc Climate Change, Management & Finance": { ielts: "7.0（单项6.5）", level: "Higher", gre: "非强制；建议90百分位，量化背景较弱者强烈建议", source: "https://www.imperial.ac.uk/business-school/masters/climate-change-management-finance/admissions/", verified: "2026-08-20" },
  "帝国理工学院|MSc Living Planet with Computational Methods in Ecology and Evolution": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computational-methods-ecology-evolution-msc/", verified: "2026-08-20" },
  "帝国理工学院|MSc Living Planet with Ecology, Evolution and Conservation": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/ecology-evolution-conservation/", verified: "2026-08-20" },
  "帝国理工学院|MSc Computing": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing/", verified: "2026-08-20" },
  "帝国理工学院|MSc Geo-Energy with Machine Learning and Data Science": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/geo-energy-machine-learning-data-science/", verified: "2026-08-20" },
  "帝国理工学院|MSc Management": { ielts: "7.0（单项6.5）", level: "Higher", gre: "建议但非强制；有良好量化成绩可不提交", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/management/", verified: "2026-08-20" },
  "帝国理工学院|Master of Public Health": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/public-health-masters/", verified: "2026-08-20" },
  "帝国理工学院|MSc Advanced Materials Science and Engineering": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/advanced-materials/", verified: "2026-08-20" },
  "帝国理工学院|MSc Machine Learning & Data Science (Online)": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/machine-learning-data-science/", verified: "2026-08-20" },
  "帝国理工学院|Medical Robotics and Image-Guided Intervention: Clinical Robotics and AI": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/clinical-robotics-ai/", verified: "2026-08-20" },
  "帝国理工学院|MSc Advanced Chemical Engineering": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/advanced-chemical-engineering/", verified: "2026-08-20" },
  "帝国理工学院|MRes Artificial Intelligence and Machine Learning": { ielts: "6.5（单项6.0）", level: "Standard", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/artificial-intelligence-machine-learning/", verified: "2026-08-20" },
  "帝国理工学院|MSc Statistics": { ielts: "7.0（单项6.5）", level: "Higher", gre: "不要求GRE/GMAT", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics/", verified: "2026-08-20" },
  "帝国理工学院|MRes Machine Learning and Big Data in the Physical Sciences": { ielts: "7.0（单项6.5）", level: "Higher", gre: "官网未说明", source: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/machine-learning-physical-sciences/", verified: "2026-08-20" }
};

window.XIPU_PROGRAM_REQUIREMENT_ALIASES = {
  "帝国理工学院|ACSE": "帝国理工学院|MSc Applied Computational Science and Engineering",
  "帝国理工学院|acse": "帝国理工学院|MSc Applied Computational Science and Engineering",
  "帝国理工学院|advanced computing": "帝国理工学院|MSc Advanced Computing",
  "帝国理工学院|Advanced Computing": "帝国理工学院|MSc Advanced Computing",
  "帝国理工学院|战略营销": "帝国理工学院|MSc Strategic Marketing",
  "帝国理工学院|Strategic Marketing": "帝国理工学院|MSc Strategic Marketing",
  "帝国理工学院|医疗机器人": "帝国理工学院|MRes in Medical Robotics and Image-Guided Intervention",
  "帝国理工学院|Medical Robotics and Image Guided Intervention": "帝国理工学院|MRes in Medical Robotics and Image-Guided Intervention",
  "帝国理工学院|MRes Medical Robotics and Image Guided Intervention": "帝国理工学院|MRes in Medical Robotics and Image-Guided Intervention",
  "帝国理工学院|Analogue and Digital Integrated Circuit Design": "帝国理工学院|MSc Analogue and Digital Integrated Circuit Design",
  "帝国理工学院|MSc Financial Technology": "帝国理工学院|MSc Financial Technology (Fintech)",
  "帝国理工学院|fintech": "帝国理工学院|MSc Financial Technology (Fintech)",
  "帝国理工学院|rmfe": "帝国理工学院|MSc Risk Management and Financial Engineering",
  "帝国理工学院|RMFE": "帝国理工学院|MSc Risk Management and Financial Engineering",
  "帝国理工学院|MSc Risk Management & Financial Engineering": "帝国理工学院|MSc Risk Management and Financial Engineering",
  "帝国理工学院|Future Power Network": "帝国理工学院|MSc Future Power Networks",
  "帝国理工学院|Future Power Networks": "帝国理工学院|MSc Future Power Networks",
  "帝国理工学院|Communication and Signal Processing": "帝国理工学院|MSc Communications and Signal Processing",
  "帝国理工学院|communication and signal processing": "帝国理工学院|MSc Communications and Signal Processing",
  "帝国理工学院|EDSML": "帝国理工学院|MSc Environmental Data Science and Machine Learning",
  "帝国理工学院|edsml": "帝国理工学院|MSc Environmental Data Science and Machine Learning",
  "帝国理工学院|Mathematics and Finance": "帝国理工学院|MSc Mathematics and Finance",
  "帝国理工学院|Applied Machine Learning": "帝国理工学院|MSc Applied Machine Learning",
  "帝国理工学院|Applied Mathematics": "帝国理工学院|MSc Applied Mathematics",
  "帝国理工学院|Artificial Intelligence Applications and Innovation": "帝国理工学院|MSc Artificial Intelligence Applications and Innovation",
  "帝国理工学院|控制与优化": "帝国理工学院|MSc Control and Optimisation",
  "帝国理工学院|Human and Biological Robotics": "帝国理工学院|MSc Human and Biological Robotics",
  "帝国理工学院|Renewable Energy with AI and Data Science: Geology and Geophysics": "帝国理工学院|MSc Renewable Energy with AI and Data Science: Geology and Geophysics",
  "帝国理工学院|Computing": "帝国理工学院|MSc Computing",
  "帝国理工学院|computing": "帝国理工学院|MSc Computing",
  "帝国理工学院|GEMS": "帝国理工学院|MSc Geo-Energy with Machine Learning and Data Science",
  "帝国理工学院|gems": "帝国理工学院|MSc Geo-Energy with Machine Learning and Data Science",
  "帝国理工学院|战略市场营销": "帝国理工学院|MSc Strategic Marketing",
  "帝国理工学院|Future power networks": "帝国理工学院|MSc Future Power Networks",
  "帝国理工学院|Communications and Signal Processing": "帝国理工学院|MSc Communications and Signal Processing",
  "帝国理工学院|Control and optimization": "帝国理工学院|MSc Control and Optimisation",
  "帝国理工学院|安全与复原": "帝国理工学院|MSc Security and Resilience: Science and Technology",
  "帝国理工学院|模拟与数字集成电路设计": "帝国理工学院|MSc Analogue and Digital Integrated Circuit Design",
  "帝国理工学院|Environmental data science and machine learning": "帝国理工学院|MSc Environmental Data Science and Machine Learning",
  "帝国理工学院|soft electronic materials": "帝国理工学院|MRes Soft Electronic Materials",
  "帝国理工学院|transport": "帝国理工学院|MSc Transport",
  "帝国理工学院|MRes in Machine Learning and Big Data in the Physical Sciences": "帝国理工学院|MRes Machine Learning and Big Data in the Physical Sciences"
};
